# After registering a name on build.snapcraft.io, commit an uncommented line:
name: molden
version: '5.8' # just for humans, typically '1.2+git' or '1.3.2'
summary: Molden is a package for displaying Molecular Density.
description: Molden is a package for displaying Molecular Density from the Ab Initio packages GAMESS-UK , GAMESS-US and GAUSSIAN and the Semi-Empirical packages Mopac/Ampac, it also supports a number of other programs via the Molden Format. Molden reads all the required information from the GAMESS / GAUSSIAN outputfile.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

parts:
  molden:
    plugin: dump
    source: ftp://ftp.cmbi.umcn.nl/pub/molgraph/molden/bin/Linux/molden5.8.ubuntu.64.tar.gz
    stage-packages:
      - g++
#      - make
      - gfortran
      - libx11-6
#      - libx11-dev
      - libgl1-mesa-glx
#      - libgl1-mesa-dev
#      - build-essential
#      - mesa-common-dev
#      - libglu1-mesa-dev
#      - libxmu-dev
#      - xutils-dev

apps:
  molden:
    command: molden
